/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package amit.kafka.avro.types;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DeliveryAddress extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5420323514141881351L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeliveryAddress\",\"namespace\":\"amit.kafka.avro.types\",\"fields\":[{\"name\":\"AddressLine\",\"type\":[\"null\",\"string\"]},{\"name\":\"city\",\"type\":[\"null\",\"string\"]},{\"name\":\"state\",\"type\":[\"null\",\"string\"]},{\"name\":\"PinCode\",\"type\":[\"null\",\"string\"]},{\"name\":\"contactNumber\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence AddressLine;
  @Deprecated public java.lang.CharSequence city;
  @Deprecated public java.lang.CharSequence state;
  @Deprecated public java.lang.CharSequence PinCode;
  @Deprecated public java.lang.CharSequence contactNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeliveryAddress() {}

  /**
   * All-args constructor.
   * @param AddressLine The new value for AddressLine
   * @param city The new value for city
   * @param state The new value for state
   * @param PinCode The new value for PinCode
   * @param contactNumber The new value for contactNumber
   */
  public DeliveryAddress(java.lang.CharSequence AddressLine, java.lang.CharSequence city, java.lang.CharSequence state, java.lang.CharSequence PinCode, java.lang.CharSequence contactNumber) {
    this.AddressLine = AddressLine;
    this.city = city;
    this.state = state;
    this.PinCode = PinCode;
    this.contactNumber = contactNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return AddressLine;
    case 1: return city;
    case 2: return state;
    case 3: return PinCode;
    case 4: return contactNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: AddressLine = (java.lang.CharSequence)value$; break;
    case 1: city = (java.lang.CharSequence)value$; break;
    case 2: state = (java.lang.CharSequence)value$; break;
    case 3: PinCode = (java.lang.CharSequence)value$; break;
    case 4: contactNumber = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'AddressLine' field.
   * @return The value of the 'AddressLine' field.
   */
  public java.lang.CharSequence getAddressLine() {
    return AddressLine;
  }

  /**
   * Sets the value of the 'AddressLine' field.
   * @param value the value to set.
   */
  public void setAddressLine(java.lang.CharSequence value) {
    this.AddressLine = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }

  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return The value of the 'state' field.
   */
  public java.lang.CharSequence getState() {
    return state;
  }

  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'PinCode' field.
   * @return The value of the 'PinCode' field.
   */
  public java.lang.CharSequence getPinCode() {
    return PinCode;
  }

  /**
   * Sets the value of the 'PinCode' field.
   * @param value the value to set.
   */
  public void setPinCode(java.lang.CharSequence value) {
    this.PinCode = value;
  }

  /**
   * Gets the value of the 'contactNumber' field.
   * @return The value of the 'contactNumber' field.
   */
  public java.lang.CharSequence getContactNumber() {
    return contactNumber;
  }

  /**
   * Sets the value of the 'contactNumber' field.
   * @param value the value to set.
   */
  public void setContactNumber(java.lang.CharSequence value) {
    this.contactNumber = value;
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static amit.kafka.avro.types.DeliveryAddress.Builder newBuilder() {
    return new amit.kafka.avro.types.DeliveryAddress.Builder();
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static amit.kafka.avro.types.DeliveryAddress.Builder newBuilder(amit.kafka.avro.types.DeliveryAddress.Builder other) {
    return new amit.kafka.avro.types.DeliveryAddress.Builder(other);
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder by copying an existing DeliveryAddress instance.
   * @param other The existing instance to copy.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static amit.kafka.avro.types.DeliveryAddress.Builder newBuilder(amit.kafka.avro.types.DeliveryAddress other) {
    return new amit.kafka.avro.types.DeliveryAddress.Builder(other);
  }

  /**
   * RecordBuilder for DeliveryAddress instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeliveryAddress>
    implements org.apache.avro.data.RecordBuilder<DeliveryAddress> {

    private java.lang.CharSequence AddressLine;
    private java.lang.CharSequence city;
    private java.lang.CharSequence state;
    private java.lang.CharSequence PinCode;
    private java.lang.CharSequence contactNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(amit.kafka.avro.types.DeliveryAddress.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.AddressLine)) {
        this.AddressLine = data().deepCopy(fields()[0].schema(), other.AddressLine);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.PinCode)) {
        this.PinCode = data().deepCopy(fields()[3].schema(), other.PinCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.contactNumber)) {
        this.contactNumber = data().deepCopy(fields()[4].schema(), other.contactNumber);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DeliveryAddress instance
     * @param other The existing instance to copy.
     */
    private Builder(amit.kafka.avro.types.DeliveryAddress other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.AddressLine)) {
        this.AddressLine = data().deepCopy(fields()[0].schema(), other.AddressLine);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.PinCode)) {
        this.PinCode = data().deepCopy(fields()[3].schema(), other.PinCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.contactNumber)) {
        this.contactNumber = data().deepCopy(fields()[4].schema(), other.contactNumber);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'AddressLine' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddressLine() {
      return AddressLine;
    }

    /**
      * Sets the value of the 'AddressLine' field.
      * @param value The value of 'AddressLine'.
      * @return This builder.
      */
    public amit.kafka.avro.types.DeliveryAddress.Builder setAddressLine(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.AddressLine = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'AddressLine' field has been set.
      * @return True if the 'AddressLine' field has been set, false otherwise.
      */
    public boolean hasAddressLine() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'AddressLine' field.
      * @return This builder.
      */
    public amit.kafka.avro.types.DeliveryAddress.Builder clearAddressLine() {
      AddressLine = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }

    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public amit.kafka.avro.types.DeliveryAddress.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.city = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public amit.kafka.avro.types.DeliveryAddress.Builder clearCity() {
      city = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * @return The value.
      */
    public java.lang.CharSequence getState() {
      return state;
    }

    /**
      * Sets the value of the 'state' field.
      * @param value The value of 'state'.
      * @return This builder.
      */
    public amit.kafka.avro.types.DeliveryAddress.Builder setState(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.state = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'state' field.
      * @return This builder.
      */
    public amit.kafka.avro.types.DeliveryAddress.Builder clearState() {
      state = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'PinCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPinCode() {
      return PinCode;
    }

    /**
      * Sets the value of the 'PinCode' field.
      * @param value The value of 'PinCode'.
      * @return This builder.
      */
    public amit.kafka.avro.types.DeliveryAddress.Builder setPinCode(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.PinCode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'PinCode' field has been set.
      * @return True if the 'PinCode' field has been set, false otherwise.
      */
    public boolean hasPinCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'PinCode' field.
      * @return This builder.
      */
    public amit.kafka.avro.types.DeliveryAddress.Builder clearPinCode() {
      PinCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'contactNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getContactNumber() {
      return contactNumber;
    }

    /**
      * Sets the value of the 'contactNumber' field.
      * @param value The value of 'contactNumber'.
      * @return This builder.
      */
    public amit.kafka.avro.types.DeliveryAddress.Builder setContactNumber(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.contactNumber = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'contactNumber' field has been set.
      * @return True if the 'contactNumber' field has been set, false otherwise.
      */
    public boolean hasContactNumber() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'contactNumber' field.
      * @return This builder.
      */
    public amit.kafka.avro.types.DeliveryAddress.Builder clearContactNumber() {
      contactNumber = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public DeliveryAddress build() {
      try {
        DeliveryAddress record = new DeliveryAddress();
        record.AddressLine = fieldSetFlags()[0] ? this.AddressLine : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.city = fieldSetFlags()[1] ? this.city : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.state = fieldSetFlags()[2] ? this.state : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.PinCode = fieldSetFlags()[3] ? this.PinCode : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.contactNumber = fieldSetFlags()[4] ? this.contactNumber : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
